const palabras = [
    { palabra_wuayuunaiki: "A'katalaa", palabra_espanol: "Aislar - separar" },
    { palabra_wuayuunaiki: "A>ataa", palabra_espanol: "Poner, colocar." },
    { palabra_wuayuunaiki: "A>i", palabra_espanol: "Yuca" },
    { palabra_wuayuunaiki: "A>ii", palabra_espanol: "Diente" },
    { palabra_wuayuunaiki: "A>iin", palabra_espanol: "Corazón" },
    { palabra_wuayuunaiki: "A>injaa", palabra_espanol: "Hacer" },
    { palabra_wuayuunaiki: "A>inmajaa", palabra_espanol: "Cuidar" },
    { palabra_wuayuunaiki: "A>najaa", palabra_espanol: "Guardar" },
    { palabra_wuayuunaiki: "A>pulaa", palabra_espanol: "Arma de fuego." },
    { palabra_wuayuunaiki: "A>ulu", palabra_espanol: "Suegra" },
    { palabra_wuayuunaiki: "A>yalajaa", palabra_espanol: "Comprar" },
    { palabra_wuayuunaiki: "A>yapujaa", palabra_espanol: "Coser" },
    { palabra_wuayuunaiki: "A>yatawaa", palabra_espanol: "Trabajar" },
    { palabra_wuayuunaiki: "A>yateeraa", palabra_espanol: "Mandar a trabajar" },
    { palabra_wuayuunaiki: "Aa>inraamaajatü", palabra_espanol: "Adverbio" },
    { palabra_wuayuunaiki: "Aa>inralaakat", palabra_espanol: "Predicado" },
    { palabra_wuayuunaiki: "Aajaa", palabra_espanol: "Quemar." },
    { palabra_wuayuunaiki: "Aamajaa", palabra_espanol: "Hacer dieta." },
    { palabra_wuayuunaiki: "Aanalaa", palabra_espanol: "Sábana" },
    { palabra_wuayuunaiki: "Aanawua", palabra_espanol: "Vestirse-arreglarse" },
    { palabra_wuayuunaiki: "Aanut", palabra_espanol: "Tejedor" },
    { palabra_wuayuunaiki: "Aapajaa", palabra_espanol: "Escuchar-oír" },
    { palabra_wuayuunaiki: "Aapiraa", palabra_espanol: "Avisar" },
    {
        palabra_wuayuunaiki: "Aapiraawa",
        palabra_espanol: "Forzajear, lucha libre",
    },
    { palabra_wuayuunaiki: "Aashajawaa", palabra_espanol: "Hablar" },
    { palabra_wuayuunaiki: "Aawalaa", palabra_espanol: "Cabello" },
    { palabra_wuayuunaiki: "Achajawaa", palabra_espanol: "Buscar" },
    { palabra_wuayuunaiki: "Achatajaa", palabra_espanol: "Romper" },
    { palabra_wuayuunaiki: "Ache>e", palabra_espanol: "Oreja" },
    { palabra_wuayuunaiki: "Ache>ese", palabra_espanol: "Arete" },
    { palabra_wuayuunaiki: "Achiki", palabra_espanol: "Historia" },
    {
        palabra_wuayuunaiki: "Achinkaa-Anülia",
        palabra_espanol: "Nombre para persona.",
    },
    { palabra_wuayuunaiki: "Achira", palabra_espanol: "Senos" },
    { palabra_wuayuunaiki: "Achon", palabra_espanol: "Hijo" },
    { palabra_wuayuunaiki: "Achujaa", palabra_espanol: "Celar" },
    { palabra_wuayuunaiki: "Achulaa", palabra_espanol: "Besar" },
    { palabra_wuayuunaiki: "Achunkajaa", palabra_espanol: "Chupar-masticar" },
    { palabra_wuayuunaiki: "Achüüin", palabra_espanol: "Riñón" },
    { palabra_wuayuunaiki: "Aipa>a", palabra_espanol: "Noche" },
    { palabra_wuayuunaiki: "Aipia", palabra_espanol: "Árbol Trupillo" },
    { palabra_wuayuunaiki: "Aipirua", palabra_espanol: "Número seis (6)" },
    { palabra_wuayuunaiki: "Airü", palabra_espanol: "Tía" },
    { palabra_wuayuunaiki: "Aja>ttiria", palabra_espanol: "Complemento" },
    { palabra_wuayuunaiki: "Ajapú", palabra_espanol: "Mano" },
    { palabra_wuayuunaiki: "Ajujaa", palabra_espanol: "Teñir" },
    { palabra_wuayuunaiki: "Ajülüwaa", palabra_espanol: "Pareja" },
    { palabra_wuayuunaiki: "Ajutapu>ukana", palabra_espanol: "Electores" },
    { palabra_wuayuunaiki: "Ajutunaa", palabra_espanol: "Expulsar, votar" },
    { palabra_wuayuunaiki: "Ajutuu, aaliaa", palabra_espanol: "Derechos." },
    { palabra_wuayuunaiki: "Akaajasü", palabra_espanol: "Acabar, terminar" },
    { palabra_wuayuunaiki: "Akounjaa", palabra_espanol: "Fumar." },
    {
        palabra_wuayuunaiki: "Ako>umüinjia",
        palabra_espanol: "Aumentar la cantidad de algo.",
    },
    { palabra_wuayuunaiki: "Ako>umüinjoa", palabra_espanol: "Sumar." },
    { palabra_wuayuunaiki: "Akomüinjaa", palabra_espanol: "Aumentar" },
    { palabra_wuayuunaiki: "Aku>leejaa", palabra_espanol: "Flojear" },
    { palabra_wuayuunaiki: "Aküjalaa", palabra_espanol: "Texto" },
    { palabra_wuayuunaiki: "Aküjalaachon", palabra_espanol: "Párrafo" },
    {
        palabra_wuayuunaiki: "Aküjiaa",
        palabra_espanol: "Artículo constitucional",
    },
    { palabra_wuayuunaiki: "Akuleemeraa", palabra_espanol: "Sonreír" },
    { palabra_wuayuunaiki: "Akulejaa", palabra_espanol: "Torcedura" },
    { palabra_wuayuunaiki: "Akumajaa", palabra_espanol: "Construir, arreglo" },
    { palabra_wuayuunaiki: "Akumajalaa", palabra_espanol: "Producción" },
    { palabra_wuayuunaiki: "Ala>ajia", palabra_espanol: "Borrador." },
    { palabra_wuayuunaiki: "Alaa", palabra_espanol: "Mentiroso" },
    { palabra_wuayuunaiki: "Alaawa", palabra_espanol: "Mentira" },
    { palabra_wuayuunaiki: "Alakajaa", palabra_espanol: "Cocinar" },
    { palabra_wuayuunaiki: "Alamajaa", palabra_espanol: "Gatear" },
    { palabra_wuayuunaiki: "Alamalo>u", palabra_espanol: "Ceja" },
    { palabra_wuayuunaiki: "Alaüla", palabra_espanol: "Tío" },
    { palabra_wuayuunaiki: "Ale>e", palabra_espanol: "Estómago" },
    { palabra_wuayuunaiki: "Ale>ejaa", palabra_espanol: "Regresar" },
    { palabra_wuayuunaiki: "Ale>ewasü", palabra_espanol: "Artículo" },
    { palabra_wuayuunaiki: "Aleepü", palabra_espanol: "Cuchara wayuu" },
    { palabra_wuayuunaiki: "Aleewa", palabra_espanol: "Amigo" },
    { palabra_wuayuunaiki: "Alialü", palabra_espanol: "Media noche" },
    { palabra_wuayuunaiki: "Alii", palabra_espanol: "Querer, cariño." },
    { palabra_wuayuunaiki: "Aliichajaa", palabra_espanol: "Ordeñar" },
    { palabra_wuayuunaiki: "Aliika", palabra_espanol: "Tarde de ocaso." },
    {
        palabra_wuayuunaiki: "Aliitaa>ulia",
        palabra_espanol: "Árbol de calabaza.",
    },
    {
        palabra_wuayuunaiki: "Alijuna",
        palabra_espanol: "Perteneciente a la cultura occidental",
    },
    { palabra_wuayuunaiki: "Alu>uwajaa", palabra_espanol: "Robar" },
    {
        palabra_wuayuunaiki: "Alu>uwanaa",
        palabra_espanol: "Recolectar iguaraya",
    },
    { palabra_wuayuunaiki: "Alu>uwataa", palabra_espanol: "Mandar" },
    { palabra_wuayuunaiki: "Alüiuyuu", palabra_espanol: "Cuñada" },
    { palabra_wuayuunaiki: "Alijirawa", palabra_espanol: "Negarse" },
    { palabra_wuayuunaiki: "Ama", palabra_espanol: "Caballo" },
    {
        palabra_wuayuunaiki: "Amarulu>u",
        palabra_espanol: "Comunidad de Nazareth",
    },
    { palabra_wuayuunaiki: "Amostsajirawaa", palabra_espanol: "Restar" },
    {
        palabra_wuayuunaiki: "Amotsajia",
        palabra_espanol: "Minorar o recortar.",
    },
    { palabra_wuayuunaiki: "Amuchi", palabra_espanol: "Múcura" },
    { palabra_wuayuunaiki: "Amuyuu", palabra_espanol: "Cementerio wayuu." },
    { palabra_wuayuunaiki: "Anaa a>yataain", palabra_espanol: "Buena gestión" },
    { palabra_wuayuunaiki: "Anaa", palabra_espanol: "Bueno" },
    { palabra_wuayuunaiki: "Anaajiakaa", palabra_espanol: "Organización" },
    { palabra_wuayuunaiki: "Anakajaa", palabra_espanol: "Chistoso" },
    { palabra_wuayuunaiki: "Ananajaa", palabra_espanol: "Mirar-ver" },
    { palabra_wuayuunaiki: "Aniijaa", palabra_espanol: "Reunir" },
    { palabra_wuayuunaiki: "Anneerü", palabra_espanol: "Ovejo" },
    { palabra_wuayuunaiki: "Antaa", palabra_espanol: "Llegar" },
    { palabra_wuayuunaiki: "Antiruushi", palabra_espanol: "Importaciones" },
    { palabra_wuayuunaiki: "Anua", palabra_espanol: "Barco" },
    { palabra_wuayuunaiki: "Anülia a>iratia", palabra_espanol: "Pronombre" },
    { palabra_wuayuunaiki: "Anüliaa", palabra_espanol: "Sustantivo" },
    { palabra_wuayuunaiki: "Anüliaamaajatü", palabra_espanol: "Adjetivo" },
    { palabra_wuayuunaiki: "Apaa", palabra_espanol: "Dar, entregar" },
    { palabra_wuayuunaiki: "Apanaa", palabra_espanol: "Hígado" },
    { palabra_wuayuunaiki: "Apolajoo", palabra_espanol: "Hervir" },
    { palabra_wuayuunaiki: "Apu>ujaayaasü", palabra_espanol: "Inclinado" },
    { palabra_wuayuunaiki: "Apünaa", palabra_espanol: "Camino" },
    { palabra_wuayuunaiki: "Apúnajaa", palabra_espanol: "Sembrar, cultivar" },
    {
        palabra_wuayuunaiki: "Apünüin ko>upunaasü",
        palabra_espanol: "Triángulo",
    },
    { palabra_wuayuunaiki: "Apünüin", palabra_espanol: "Número tres (3)" },
    {
        palabra_wuayuunaiki: "Apüsajaa-Atsajaa",
        palabra_espanol: "Descoser, safar, abrir",
    },
    { palabra_wuayuunaiki: "Asa>a", palabra_espanol: "Pierna" },
    {
        palabra_wuayuunaiki: "Asaa",
        palabra_espanol: "Beber, tomar alguna bebida líquida.",
    },
    { palabra_wuayuunaiki: "Asaca", palabra_espanol: "Saludar" },
    {
        palabra_wuayuunaiki: "Asakaalajaa",
        palabra_espanol: "Recolectar yotojoro",
    },
    { palabra_wuayuunaiki: "Asakajaa", palabra_espanol: "Convidar, contratar" },
    { palabra_wuayuunaiki: "Asakiria", palabra_espanol: "Interrogación" },
    { palabra_wuayuunaiki: "Asapa>in", palabra_espanol: "Rodilla" },
    { palabra_wuayuunaiki: "Asapatse", palabra_espanol: "Zapato" },
    {
        palabra_wuayuunaiki: "Asasajia",
        palabra_espanol: "Colador de colar alimento.",
    },
    { palabra_wuayuunaiki: "Ashaitajaa", palabra_espanol: "Jugar" },
    { palabra_wuayuunaiki: "Ashajaa", palabra_espanol: "Escribir" },
    { palabra_wuayuunaiki: "Ashajaaushi", palabra_espanol: "Oralidad" },
    { palabra_wuayuunaiki: "Ashaje>eraa", palabra_espanol: "Leer" },
    {
        palabra_wuayuunaiki: "Ashajia",
        palabra_espanol: "Lápiz, bolígrafo, tiza, grafo",
    },
    { palabra_wuayuunaiki: "Ashajiapülee", palabra_espanol: "Tablero" },
    { palabra_wuayuunaiki: "Ashajiria", palabra_espanol: "Dictado" },
    { palabra_wuayuunaiki: "Ashakataa", palabra_espanol: "Bajarse" },
    { palabra_wuayuunaiki: "Ashanawaa", palabra_espanol: "Tropezar" },
    { palabra_wuayuunaiki: "Ashapaje>eraa", palabra_espanol: "Apurar" },
    { palabra_wuayuunaiki: "Ashataa", palabra_espanol: "Copiar, imitar" },
    { palabra_wuayuunaiki: "Ashataa", palabra_espanol: "Curar" },
    {
        palabra_wuayuunaiki: "Ashataa",
        palabra_espanol: "Imitar, sanar, culminar",
    },
    { palabra_wuayuunaiki: "Ashatawaa", palabra_espanol: "Partir, quebrar." },
    { palabra_wuayuunaiki: "Ashatüsü", palabra_espanol: "Terminar algo" },
    {
        palabra_wuayuunaiki: "Ashajawaa",
        palabra_espanol: "Maquillarse el rostro",
    },
    { palabra_wuayuunaiki: "Ashe>in", palabra_espanol: "Vestido" },
    { palabra_wuayuunaiki: "Ashii", palabra_espanol: "Padre o papá" },
    { palabra_wuayuunaiki: "Ashiitaa", palabra_espanol: "Orinar" },
    { palabra_wuayuunaiki: "Ashijaawa", palabra_espanol: "Lavar" },
    { palabra_wuayuunaiki: "Ashuujaa", palabra_espanol: "Sancochar" },
    { palabra_wuayuunaiki: "Ashuunajaa", palabra_espanol: "Bañarse" },
    { palabra_wuayuunaiki: "Asirujaa", palabra_espanol: "Triturar" },
    {
        palabra_wuayuunaiki: "Asirujia",
        palabra_espanol: "Objeto donde se tritura",
    },
    { palabra_wuayuunaiki: "Asiruu", palabra_espanol: "Asesinado." },
    { palabra_wuayuunaiki: "Asukaa", palabra_espanol: "Buscar leña" },
    { palabra_wuayuunaiki: "Asülajaa", palabra_espanol: "Regalar" },
    {
        palabra_wuayuunaiki: "Asütnawaa",
        palabra_espanol: "Quitarse, retirarse, alejarse.",
    },
    { palabra_wuayuunaiki: "Atujaa", palabra_espanol: "Eficacia" },
    { palabra_wuayuunaiki: "Atkawaa", palabra_espanol: "Pelear" },
    { palabra_wuayuunaiki: "Atpajaa", palabra_espanol: "Recolectar frutos" },
    { palabra_wuayuunaiki: "Atpana", palabra_espanol: "Conejo" },
    { palabra_wuayuunaiki: "Atujaa so>u", palabra_espanol: "Matemática" },
    { palabra_wuayuunaiki: "Atújaa", palabra_espanol: "Saber" },
    { palabra_wuayuunaiki: "Atunkaa", palabra_espanol: "Dormir" },
    { palabra_wuayuunaiki: "Atuushi", palabra_espanol: "Abuelo" },
    { palabra_wuayuunaiki: "A>ui", palabra_espanol: "Suegro" },
    { palabra_wuayuunaiki: "Aulijanaa", palabra_espanol: "Collar" },
    { palabra_wuayuunaiki: "Aülü", palabra_espanol: "Suegra" },
    { palabra_wuayuunaiki: "Attia", palabra_espanol: "Semilla" },
    { palabra_wuayuunaiki: "Awa>alaa", palabra_espanol: "Rajar" },
    { palabra_wuayuunaiki: "Awaataa", palabra_espanol: "Gritar" },
    { palabra_wuayuunaiki: "Awainmajirawaa", palabra_espanol: "Multiplicar" },
    { palabra_wuayuunaiki: "Awalaa", palabra_espanol: "Hermano" },
    { palabra_wuayuunaiki: "Awataa", palabra_espanol: "Tocar, aplaudir" },
    { palabra_wuayuunaiki: "Awataa", palabra_espanol: "Volar" },
    { palabra_wuayuunaiki: "Awatawaa", palabra_espanol: "Correr" },
    { palabra_wuayuunaiki: "Awawajia", palabra_espanol: "Abanico" },
    { palabra_wuayuunaiki: "Awayuusee", palabra_espanol: "Esposa" },
    { palabra_wuayuunaiki: "Ayalajaa", palabra_espanol: "Llorar" },
    { palabra_wuayuunaiki: "Ayanamajaa", palabra_espanol: "Trabajar" },
    { palabra_wuayuunaiki: "Ayataa", palabra_espanol: "Ser idéntico." },
    { palabra_wuayuunaiki: "Ayonnajaa", palabra_espanol: "Bailar." },
    { palabra_wuayuunaiki: "Ayüüjawaa", palabra_espanol: "Moler" },
    { palabra_espanol: "Allá", palabra_wuayuunaiki: "Cha>aya" },
    { palabra_espanol: "Abundancia", palabra_wuayuunaiki: "Cha>laasü" },
    { palabra_espanol: "Machete", palabra_wuayuunaiki: "Chajaruuta" },
    { palabra_espanol: "Bruja", palabra_wuayuunaiki: "Chama>a" },
    { palabra_espanol: "Personaje mítico", palabra_wuayuunaiki: "Chamaa" },
    { palabra_espanol: "Hacia allá", palabra_wuayuunaiki: "Chamüin" },
    { palabra_espanol: "Por allá", palabra_wuayuunaiki: "Chapüna" },
    { palabra_espanol: "Dámelo", palabra_wuayuunaiki: "Che>era" },
    { palabra_espanol: "Arete", palabra_wuayuunaiki: "Che>esa" },
    { palabra_espanol: "Duro", palabra_wuayuunaiki: "Checheesü" },
    { palabra_espanol: "Del otro lado", palabra_wuayuunaiki: "Cheje>eruu" },
    { palabra_espanol: "De allá", palabra_wuayuunaiki: "Chejeeyaa" },
    { palabra_espanol: "Aquel-distante", palabra_wuayuunaiki: "Chia" },
    { palabra_espanol: "Este", palabra_wuayuunaiki: "Chii" },
    { palabra_espanol: "Leche materna", palabra_wuayuunaiki: "Chiiraa" },
    { palabra_espanol: "Chivo criado", palabra_wuayuunaiki: "Chime>e" },
    { palabra_espanol: "Brillar", palabra_wuayuunaiki: "Chimiitaa" },
    { palabra_espanol: "Parpadear", palabra_wuayuunaiki: "Chimiitüsü" },
    { palabra_espanol: "Falta", palabra_wuayuunaiki: "Cho>ujaa" },
    { palabra_espanol: "Trompo", palabra_wuayuunaiki: "Chochoo" },
    { palabra_espanol: "Estar afligido", palabra_wuayuunaiki: "Choloosü" },
    {
        palabra_espanol: "Dentro de",
        palabra_wuayuunaiki: "Cholootusü/Chapatsü",
    },
    { palabra_espanol: "Dentro de líquidos", palabra_wuayuunaiki: "Cholotüsü" },
    { palabra_espanol: "Picar - Arreglar", palabra_wuayuunaiki: "Chontaa" },
    { palabra_espanol: "Pájaro carpintero", palabra_wuayuunaiki: "Choochoo" },
    { palabra_espanol: "Garza blanca", palabra_wuayuunaiki: "Chotchot" },
    { palabra_espanol: "Prendido", palabra_wuayuunaiki: "Chuataa" },
    { palabra_espanol: "Olor a chivato", palabra_wuayuunaiki: "Chuateemasü" },
    { palabra_espanol: "Resbaloso", palabra_wuayuunaiki: "Chüchüsü" },
    { palabra_espanol: "Tener diarrea", palabra_wuayuunaiki: "Chüliittaa" },
    { palabra_espanol: "Colibrí", palabra_wuayuunaiki: "Chúnü>ü" },
    { palabra_espanol: "Mojado", palabra_wuayuunaiki: "Chütsü" },
    { palabra_espanol: "Pangado", palabra_wuayuunaiki: "Chuweerasü" },
    { palabra_espanol: "Sabor", palabra_wuayuunaiki: "E>ejü" },
    { palabra_espanol: "Lame", palabra_wuayuunaiki: "E>erujaa" },
    { palabra_espanol: "Ver", palabra_wuayuunaiki: "E>iaa" },
    { palabra_espanol: "Marido", palabra_wuayuunaiki: "E>ichi" },
    { palabra_espanol: "Nariz", palabra_wuayuunaiki: "E>ichii" },
    { palabra_espanol: "Salar", palabra_wuayuunaiki: "E>ichiijaa" },
    { palabra_espanol: "Tener diarrea", palabra_wuayuunaiki: "E>ijaa" },
    { palabra_espanol: "Llevar", palabra_wuayuunaiki: "E>ikaa" },
    { palabra_espanol: "Herida", palabra_wuayuunaiki: "E>ikawa" },
    { palabra_espanol: "Profesor", palabra_wuayuunaiki: "E>ikui" },
    { palabra_espanol: "Salón", palabra_wuayuunaiki: "E>ikuleepala" },
    { palabra_espanol: "Alumno", palabra_wuayuunaiki: "E>ikunüii" },
    { palabra_espanol: "Ofender", palabra_wuayuunaiki: "E>imaa" },
    { palabra_espanol: "Boca", palabra_wuayuunaiki: "E>imataa" },
    { palabra_espanol: "Labios", palabra_wuayuunaiki: "E>imataa" },
    { palabra_espanol: "Tejer", palabra_wuayuunaiki: "E>inaa" },
    { palabra_espanol: "Tejer-tirar", palabra_wuayuunaiki: "E>inaaa" },
    { palabra_espanol: "Tirotear", palabra_wuayuunaiki: "E>inajirawaa" },
    { palabra_espanol: "Posaderas-glúteos", palabra_wuayuunaiki: "E>inalu>u" },
    { palabra_espanol: "Silla", palabra_wuayuunaiki: "E>inasee" },
    { palabra_espanol: "Eructar", palabra_wuayuunaiki: "E>inawaa" },
    { palabra_espanol: "Ministros", palabra_wuayuunaiki: "E>ipejeejanaa" },
    { palabra_espanol: "Escaparse", palabra_wuayuunaiki: "E>ipirawaa" },
    { palabra_espanol: "Frente", palabra_wuayuunaiki: "E>ipo>u" },
    { palabra_espanol: "Enemigo", palabra_wuayuunaiki: "E>ipolojoo" },
    { palabra_espanol: "Enemigo-tapa", palabra_wuayuunaiki: "E>ipoloo" },
    { palabra_espanol: "Cantar", palabra_wuayuunaiki: "E>irajaa" },
    { palabra_espanol: "Clan", palabra_wuayuunaiki: "E>irukuu" },
    { palabra_espanol: "Acostarse", palabra_wuayuunaiki: "E>isalaa" },
    { palabra_espanol: "Cuidarse", palabra_wuayuunaiki: "E>isalajaa" },
    { palabra_espanol: "Colocar", palabra_wuayuunaiki: "E>itaa" },
    { palabra_espanol: "Defecar", palabra_wuayuunaiki: "E>itaa" },
    { palabra_espanol: "Colocar", palabra_wuayuunaiki: "E>itanaa" },
    { palabra_espanol: "Regresar", palabra_wuayuunaiki: "E>itawaa" },
    { palabra_espanol: "Mostrar", palabra_wuayuunaiki: "Eiyataa" },
    { palabra_espanol: "Visita", palabra_wuayuunaiki: "E>iyou" },
    { palabra_espanol: "Amarrar", palabra_wuayuunaiki: "E>jitaawa" },
    { palabra_espanol: "Conquistar-enamorar", palabra_wuayuunaiki: "E> mejaa" },
    { palabra_espanol: "Embriagarse", palabra_wuayuunaiki: "E> peraa" },
    { palabra_espanol: "Conocer", palabra_wuayuunaiki: "E>rajaa" },
    { palabra_espanol: "Llamar", palabra_wuayuunaiki: "Eenakaa" },
    { palabra_espanol: "Incendio", palabra_wuayuunaiki: "Eeperajawaa" },
    { palabra_espanol: "Haber-estar", palabra_wuayuunaiki: "Eewa" },
    { palabra_espanol: "Madre", palabra_wuayuunaiki: "Eii" },
    { palabra_espanol: "Accidente", palabra_wuayuunaiki: "Eewawaa" },
    { palabra_espanol: "Clase", palabra_wuayuunaiki: "Eikalaa" },
    { palabra_espanol: "Profesor", palabra_wuayuunaiki: "Eiküi" },
    { palabra_espanol: "Colgar", palabra_wuayuunaiki: "Eimajaa" },
    { palabra_espanol: "Huesos", palabra_wuayuunaiki: "Eipüsee" },
    { palabra_espanol: "Mirar", palabra_wuayuunaiki: "Eirakawaa" },
    { palabra_espanol: "Maracas", palabra_wuayuunaiki: "Eishiraa" },
    {
        palabra_espanol: "Definir establecer",
        palabra_wuayuunaiki: "Eitawaa sukua>ipa",
    },
    { palabra_espanol: "Curar", palabra_wuayuunaiki: "Eiyajaa" },
    { palabra_espanol: "Curarse", palabra_wuayuunaiki: "Eiyajawaa" },
    { palabra_espanol: "Medico-sanado", palabra_wuayuunaiki: "Eiyajüi" },
    { palabra_espanol: "Comer", palabra_wuayuunaiki: "Ekaa" },
    { palabra_espanol: "Enseñar", palabra_wuayuunaiki: "Ekiirajaa" },
    { palabra_espanol: "Escuela", palabra_wuayuunaiki: "Ekirajaapülee" },
    { palabra_espanol: "Estudiante", palabra_wuayuunaiki: "Ekirajaashi" },
    { palabra_espanol: "Profesora", palabra_wuayuunaiki: "Ekirajüt" },
    { palabra_espanol: "Descansar", palabra_wuayuunaiki: "Eme>erawaa" },
    { palabra_espanol: "Engañar", palabra_wuayuunaiki: "Emeejaa" },
    { palabra_espanol: "Lloviznar", palabra_wuayuunaiki: "Ememejaa" },
    { palabra_espanol: "Receso", palabra_wuayuunaiki: "Emeraaya" },
    { palabra_espanol: "Sumergirse", palabra_wuayuunaiki: "Emerotoo" },
    { palabra_espanol: "Jugar", palabra_wuayuunaiki: "Emi>ijaa" },
    { palabra_espanol: "Prender", palabra_wuayuunaiki: "Epejaa" },
    { palabra_espanol: "Sapo", palabra_wuayuunaiki: "Eperui" },
    { palabra_espanol: "Besarse", palabra_wuayuunaiki: "Epesujawaa" },
    { palabra_espanol: "Tocar", palabra_wuayuunaiki: "Epettaa" },
    { palabra_espanol: "Casa", palabra_wuayuunaiki: "Epiaa" },
    { palabra_espanol: "Clan wayuu", palabra_wuayuunaiki: "Epieyu" },
    { palabra_espanol: "Criar", palabra_wuayuunaiki: "Epijaa" },
    { palabra_espanol: "Fonema", palabra_wuayuunaiki: "Epijanaayaa" },
    { palabra_espanol: "Llenar", palabra_wuayuunaiki: "Epirajaa" },
    { palabra_espanol: "Barrer", palabra_wuayuunaiki: "Epitajaa" },
    { palabra_espanol: "Escoba", palabra_wuayuunaiki: "Epitia/Epitajia" },
    { palabra_espanol: "Perro", palabra_wuayuunaiki: "Erü" },
    { palabra_espanol: "Vagina", palabra_wuayuunaiki: "Erü>ü" },
    { palabra_espanol: "Vomitar", palabra_wuayuunaiki: "Etaa" },
    { palabra_espanol: "Silbido", palabra_wuayuunaiki: "Eviiraa" },
    { palabra_espanol: "Sal", palabra_wuayuunaiki: "Ichii" },
    { palabra_espanol: "Planta de dividivi", palabra_wuayuunaiki: "Ichiipana" },
    { palabra_espanol: "Uribia liche>e: Duro", palabra_wuayuunaiki: "Ichipki" },
    { palabra_espanol: "Piedra", palabra_wuayuunaiki: "lipa" },
    { palabra_espanol: "Arriba", palabra_wuayuunaiki: "lipüna" },
    { palabra_espanol: "Cardenal", palabra_wuayuunaiki: "ilisho" },
    { palabra_espanol: "Totumo taza wayuu", palabra_wuayuunaiki: "lita" },
    { palabra_espanol: "Nombre de comunidad", palabra_wuayuunaiki: "litalu>u" },
    { palabra_espanol: "Animal serpiente", palabra_wuayuunaiki: "Ikaa" },
    { palabra_espanol: "Embarazada", palabra_wuayuunaiki: "Ipoluu" },
    { palabra_espanol: "Allí esta", palabra_wuayuunaiki: "Iraa" },
    { palabra_espanol: "Desabrido", palabra_wuayuunaiki: "Iraasü" },
    { palabra_espanol: "Lloriquear", palabra_wuayuunaiki: "Iralataa" },
    { palabra_espanol: "Venado", palabra_wuayuunaiki: "Irama" },
    { palabra_espanol: "Aceituna", palabra_wuayuunaiki: "Irua" },
    { palabra_espanol: "Otoño", palabra_wuayuunaiki: "Irualaa" },
    { palabra_espanol: "Nombre de wayuu", palabra_wuayuunaiki: "Irunuu" },
    { palabra_espanol: "Liberarse", palabra_wuayuunaiki: "Isaa" },
    {
        palabra_espanol: "Lugar solitario-virgen",
        palabra_wuayuunaiki: "Isashii",
    },
    { palabra_espanol: "Sangre", palabra_wuayuunaiki: "Isha" },
    { palabra_espanol: "Quemarse", palabra_wuayuunaiki: "Ishaa" },
    { palabra_espanol: "Seres misteriosos", palabra_wuayuunaiki: "Isheshe>in" },
    { palabra_espanol: "Chicha fermentada", palabra_wuayuunaiki: "Ishiruuna" },
    { palabra_espanol: "Corazón del cardón", palabra_wuayuunaiki: "Ishishula" },
    {
        palabra_espanol: "Planta medicinal amarga",
        palabra_wuayuunaiki: "Ishishuuta",
    },
    { palabra_espanol: "Rojo", palabra_wuayuunaiki: "Ishosu" },
    { palabra_espanol: "Primera", palabra_wuayuunaiki: "Iwaa" },
    { palabra_espanol: "Entre la multitud", palabra_wuayuunaiki: "Ja>akaa" },
    { palabra_espanol: "Tuqueca", palabra_wuayuunaiki: "Jaatut-" },
    { palabra_espanol: "Cereza", palabra_wuayuunaiki: "Jaipai" },
    { palabra_espanol: "Batata", palabra_wuayuunaiki: "Jaishi" },
    { palabra_espanol: "Caliente", palabra_wuayuunaiki: "Jaisü" },
    { palabra_espanol: "No importa", palabra_wuayuunaiki: "Jaitairu" },
    { palabra_espanol: "Hacia la serranía", palabra_wuayuunaiki: "Jalaala" },
    { palabra_espanol: "Con cuidado", palabra_wuayuunaiki: "Jaliian" },
    { palabra_espanol: "Liviano", palabra_wuayuunaiki: "Jamaama" },
    { palabra_espanol: "Cómo se hará", palabra_wuayuunaiki: "Jameeru" },
    { palabra_espanol: "Tuna", palabra_wuayuunaiki: "Jamüche>e" },
    { palabra_espanol: "Hambre", palabra_wuayuunaiki: "Jamuu" },
    { palabra_espanol: "Tener pena", palabra_wuayuunaiki: "Japülii" },
    { palabra_espanol: "numero Cinco", palabra_wuayuunaiki: "Jarai" },
    { palabra_espanol: "Arena fina", palabra_wuayuunaiki: "Jasai" },
    { palabra_espanol: "Acabarse", palabra_wuayuunaiki: "Jattusü" },
    { palabra_espanol: "Flecha", palabra_wuayuunaiki: "Jatü" },
    { palabra_espanol: "Pudrición", palabra_wuayuunaiki: "Jawaisü" },
    { palabra_espanol: "Pesado", palabra_wuayuunaiki: "Jawatüsü" },
    { palabra_espanol: "fruto de la tuna", palabra_wuayuunaiki: "Jayajaya" },
    { palabra_espanol: "clan wayuu", palabra_wuayuunaiki: "Jayaliiyuu" },
    { palabra_espanol: "pulga", palabra_wuayuunaiki: "Jayapa" },
    { palabra_espanol: "Sabroso", palabra_wuayuunaiki: "Jemetsü" },
    { palabra_espanol: "Frío", palabra_wuayuunaiki: "Jemiai" },
    {
        palabra_espanol: "Lugar sagrado- sitio místico",
        palabra_wuayuunaiki: "Jepira",
    },
    { palabra_espanol: "Hormiga", palabra_wuayuunaiki: "Jeyuu" },
    { palabra_espanol: "Mujer", palabra_wuayuunaiki: "Jieru" },
    { palabra_espanol: "Huesos", palabra_wuayuunaiki: "Jipü" },
    { palabra_espanol: "Planta silvestre", palabra_wuayuunaiki: "Jiisee" },
    { palabra_espanol: "Camarón", palabra_wuayuunaiki: "Jiisot" },
    { palabra_espanol: "Hilos", palabra_wuayuunaiki: "Jiitpai" },
    { palabra_espanol: "Joven", palabra_wuayuunaiki: "Jima>ai" },
    { palabra_espanol: "Tranquilidad", palabra_wuayuunaiki: "Jimataa" },
    { palabra_espanol: "Pez", palabra_wuayuunaiki: "Jime" },
    {
        palabra_espanol: "Niña en proceso de desarrollo",
        palabra_wuayuunaiki: "Jimo>olü",
    },
    { palabra_espanol: "Niño", palabra_wuayuunaiki: "Jintüi" },
    { palabra_espanol: "Niña", palabra_wuayuunaiki: "Jintut" },
    { palabra_espanol: "Planta silvestre", palabra_wuayuunaiki: "Jiruuwa" },
    { palabra_espanol: "Avispa negra", palabra_wuayuunaiki: "Jo>oma" },
    { palabra_espanol: "Pequeño", palabra_wuayuunaiki: "Jo>uchon" },
    { palabra_espanol: "Gusano", palabra_wuayuunaiki: "Jokoma" },
    { palabra_espanol: "Traquea-gañate", palabra_wuayuunaiki: "Jooraloin" },
    { palabra_espanol: "Cangrejo", palabra_wuayuunaiki: "Jorolo" },
    { palabra_espanol: "Claridad", palabra_wuayuunaiki: "Jorotta" },
    { palabra_espanol: "Iluminado", palabra_wuayuunaiki: "Jorottüi" },
    { palabra_espanol: "Expresión-yonna", palabra_wuayuunaiki: "Joseii" },
    { palabra_espanol: "Seco", palabra_wuayuunaiki: "Jososù" },
    { palabra_espanol: "Cuando", palabra_wuayuunaiki: "Jouja" },
    { palabra_espanol: "Viento", palabra_wuayuunaiki: "Joutai" },
    { palabra_espanol: "Verano", palabra_wuayuunaiki: "Joutale>ulu" },
    { palabra_espanol: "Época de brisa", palabra_wuayuunaiki: "Joutaleo>u" },
    { palabra_espanol: "Abundan", palabra_wuayuunaiki: "Joutsü" },
    { palabra_espanol: "Historia", palabra_wuayuunaiki: "Jüchikiimajatü" },
    { palabra_espanol: "Tinaja sin diseño", palabra_wuayuunaiki: "Jula>a" },
    { palabra_espanol: "Ahora", palabra_wuayuunaiki: "Jolu>u" },
    { palabra_espanol: "Revienta puerco", palabra_wuayuunaiki: "Juluwa" },
    { palabra_espanol: "Andar con", palabra_wuayuunaiki: "Jumaa" },
    { palabra_espanol: "Con", palabra_wuayuunaiki: "Jümaa" },
    { palabra_espanol: "Antiguo", palabra_wuayuunaiki: "Jumaiwajatü" },
    { palabra_espanol: "Honda wayuu", palabra_wuayuunaiki: "Junaaya" },
    { palabra_espanol: "Moscón negro", palabra_wuayuunaiki: "Junuunai" },
    { palabra_espanol: "Palomas cardoneras", palabra_wuayuunaiki: "Jurourua" },
    { palabra_espanol: "Estropajo", palabra_wuayuunaiki: "Juruula" },
    { palabra_espanol: "Reunirse", palabra_wuayuunaiki: "Jutkataa" },
    { palabra_espanol: "Árbol de mar-Mangles", palabra_wuayuunaiki: "Jutnaa" },
    {
        palabra_espanol: "Palo de revolver mazamorra",
        palabra_wuayuunaiki: "Juwalee - Jiwalee",
    },
    { palabra_espanol: "Lo cambio", palabra_wuayuunaiki: "Juwanaajain" },
    { palabra_espanol: "Lluvia", palabra_wuayuunaiki: "Juya" },
    { palabra_espanol: "Sol", palabra_wuayuunaiki: "Ka>i" },
    { palabra_espanol: "Tigre", palabra_wuayuunaiki: "Ka>laira" },
    { palabra_espanol: "Retirado", palabra_wuayuunaiki: "Ka>yatsu" },
    { palabra_espanol: "Tambor", palabra_wuayuunaiki: "Kaaha" },
    { palabra_espanol: "Alcaraván", palabra_wuayuunaiki: "Kaarai" },
    { palabra_espanol: "Colgar", palabra_wuayuunaiki: "Kachetaa" },
    { palabra_espanol: "Traer carga", palabra_wuayuunaiki: "Kachisaa" },
    { palabra_espanol: "Llevar carga", palabra_wuayuunaiki: "Kachissa" },
    { palabra_espanol: "Hierro", palabra_wuayuunaiki: "Kachueera" },
    { palabra_espanol: "Mal pechoso", palabra_wuayuunaiki: "Kainjarat" },
    { palabra_espanol: "Hacer caso", palabra_wuayuunaiki: "Kajutüinjatukat" },
    { palabra_espanol: "Calado", palabra_wuayuunaiki: "Kalakalasü" },
    { palabra_espanol: "Medio día", palabra_wuayuunaiki: "Kale>u" },
    { palabra_espanol: "Cotorra", palabra_wuayuunaiki: "Kaleekalee" },
    { palabra_espanol: "Loro", palabra_wuayuunaiki: "Kalekale" },
    { palabra_espanol: "Fruto silvestre", palabra_wuayuunaiki: "Kaliiyuu" },
    { palabra_espanol: "Demorar", palabra_wuayuunaiki: "Kama>a" },
    { palabra_espanol: "Cerro carpintero", palabra_wuayuunaiki: "Kamaichi" },
    {
        palabra_espanol: "Llamar la atención",
        palabra_wuayuunaiki: "Kamalainsu",
    },
    { palabra_espanol: "Temor", palabra_wuayuunaiki: "Kamusesü" },
    { palabra_espanol: "Diseño wayuu", palabra_wuayuunaiki: "Kanasu" },
    {
        palabra_espanol: "Mochila del hombre wayuu",
        palabra_wuayuunaiki: "Kapotera",
    },
    {
        palabra_espanol: "Actitud de respeto-prohibiciones",
        palabra_wuayuunaiki: "Kapülaunsü",
    },
    { palabra_espanol: "Difícil", palabra_wuayuunaiki: "Kapuleesü" },
    { palabra_espanol: "Amarrar", palabra_wuayuunaiki: "Kapüsü" },
    { palabra_espanol: "Olivo", palabra_wuayuunaiki: "Kapütchi" },
    { palabra_espanol: "Cuaderno", palabra_wuayuunaiki: "Karalouta" },
    { palabra_espanol: "Papel", palabra_wuayuunaiki: "Karalouta" },
    {
        palabra_espanol: "Estante,papelería,librería",
        palabra_wuayuunaiki: "Karaloutapülee",
    },
    { palabra_espanol: "Cabra", palabra_wuayuunaiki: "Kaa>ula" },
    { palabra_espanol: "Problema", palabra_wuayuunaiki: "Kasachiku" },
    { palabra_espanol: "Objeto-cosa", palabra_wuayuunaiki: "Kasakat" },
    { palabra_espanol: "Algo cortante", palabra_wuayuunaiki: "Kasasü" },
    { palabra_espanol: "Hacer silencio", palabra_wuayuunaiki: "Kaseesü" },
    { palabra_espanol: "Luna-mes", palabra_wuayuunaiki: "Kashi" },
    { palabra_espanol: "Horrible", palabra_wuayuunaiki: "Kashuulasü" },
    { palabra_espanol: "Cien pies", palabra_wuayuunaiki: "Kasipa" },
    { palabra_espanol: "Culebra cazadora", palabra_wuayuunaiki: "Kasiwano>u" },
    { palabra_espanol: "Arco iris", palabra_wuayuunaiki: "Kaspolin" },
    {
        palabra_espanol: "Expresión cultural",
        palabra_wuayuunaiki: "Kasukiahii",
    },
    { palabra_espanol: "¿Dentro de qué?", palabra_wuayuunaiki: "Kasulu>u" },
    { palabra_espanol: "Blanco", palabra_wuayuunaiki: "Kasusü" },
    {
        palabra_espanol: "Nombre de comunidad",
        palabra_wuayuunaiki: "Kasutala>in",
    },
    { palabra_espanol: "Patilla", palabra_wuayuunaiki: "Kasuusu" },
    { palabra_espanol: "Tiene fuerza.", palabra_wuayuunaiki: "Katchinsü" },
    { palabra_espanol: "Pero", palabra_wuayuunaiki: "Katia>a" },
    { palabra_espanol: "Gallina", palabra_wuayuunaiki: "Katio>u" },
    { palabra_espanol: "León", palabra_wuayuunaiki: "Katnajapüt" },
    { palabra_espanol: "Caraota guajira", palabra_wuayuunaiki: "Katsalia" },
    { palabra_espanol: "Mochila", palabra_wuayuunaiki: "Kattoui" },
    { palabra_espanol: "Odioso-antipático", palabra_wuayuunaiki: "Kaunurat" },
    { palabra_espanol: "Tener enemigos", palabra_wuayuunaiki: "Kaünüwa" },
    {
        palabra_espanol: "Tener compañero. Tener pareja.",
        palabra_wuayuunaiki: "Kawalaátasü",
    },
    { palabra_espanol: "Cactus guajiro", palabra_wuayuunaiki: "Kayuusia" },
    { palabra_espanol: "Tener piojo", palabra_wuayuunaiki: "Ke>e sü" },
    { palabra_espanol: "Primeriza", palabra_wuayuunaiki: "Ke>irumayut" },
    { palabra_espanol: "Armadillo", palabra_wuayuunaiki: "Kee>t" },
    { palabra_espanol: "Tenebroso", palabra_wuayuunaiki: "Keemasü" },
    { palabra_espanol: "Feo", palabra_wuayuunaiki: "Keemasü" },
    { palabra_espanol: "Derramar", palabra_wuayuunaiki: "Keena" },
    { palabra_espanol: "Derramarse", palabra_wuayuunaiki: "Keenasü" },
    { palabra_espanol: "Frijol", palabra_wuayuunaiki: "Keepeshuna" },
    { palabra_espanol: "Bola de fuego(mito)", palabra_wuayuunaiki: "Keeralia" },
    { palabra_espanol: "Queso", palabra_wuayuunaiki: "Keesü" },
    { palabra_espanol: "Necedad", palabra_wuayuunaiki: "Keke>eraa" },
    { palabra_espanol: "Chistoso", palabra_wuayuunaiki: "Keme>eraichi" },
    { palabra_espanol: "Carro", palabra_wuayuunaiki: "Kemion" },
    { palabra_espanol: "Café", palabra_wuayuunaiki: "Kepein / Kojee" },
    { palabra_espanol: "Vive o habita", palabra_wuayuunaiki: "Kepiasü" },
    { palabra_espanol: "Sopa-Sudor", palabra_wuayuunaiki: "Kerasü" },
    { palabra_espanol: "Terminación", palabra_wuayuunaiki: "Kettaasü" },
    { palabra_espanol: "Silbador", palabra_wuayuunaiki: "Keviirai" },
    {
        palabra_espanol: "Corteza del árbol de quina",
        palabra_wuayuunaiki: "Kiinouta",
    },
    { palabra_espanol: "Avispa", palabra_wuayuunaiki: "Ko>io" },
    { palabra_espanol: "Arropar", palabra_wuayuunaiki: "Ko>oyomaa" },
    { palabra_espanol: "Esférico-redondo", palabra_wuayuunaiki: "Ko>oyoosü" },
    { palabra_espanol: "Honda", palabra_wuayuunaiki: "Ko>ucha" },
    { palabra_espanol: "Sandalias auténticas", palabra_wuayuunaiki: "Ko>usü" },
    { palabra_espanol: "Tener hijos", palabra_wuayuunaiki: "Kochonsü" },
    { palabra_espanol: "Peludo", palabra_wuayuunaiki: "Koisü" },
    { palabra_espanol: "Espeso-leche cuajada", palabra_wuayuunaiki: "Kojoosü" },
    { palabra_espanol: "Ratón", palabra_wuayuunaiki: "Kookochet" },
    { palabra_espanol: "Vello", palabra_wuayuunaiki: "Kooli" },
    { palabra_espanol: "Escoba", palabra_wuayuunaiki: "Koowa" },
    { palabra_espanol: "Cosas de valor", palabra_wuayuunaiki: "Korolo" },
    { palabra_espanol: "Pez boca colora", palabra_wuayuunaiki: "Korookoona" },
    { palabra_espanol: "Petróleo", palabra_wuayuunaiki: "Korosin" },
    { palabra_espanol: "Tener borde", palabra_wuayuunaiki: "Kotsü" },
    { palabra_espanol: "Grupo por grupo", palabra_wuayuunaiki: "Kotta>wai" },
    { palabra_espanol: "Reunir", palabra_wuayuunaiki: "Kottaa" },
    { palabra_espanol: "Fruto de jovita", palabra_wuayuunaiki: "Koushole" },
    { palabra_espanol: "Tupido", palabra_wuayuunaiki: "Kuisü" },
    { palabra_espanol: "Piedras del fogón", palabra_wuayuunaiki: "Küliki" },
    { palabra_espanol: "Lagartija", palabra_wuayuunaiki: "Kulu" },
    { palabra_espanol: "Machorrito", palabra_wuayuunaiki: "Kulumashat" },
    { palabra_espanol: "Tela", palabra_wuayuunaiki: "Kuluulu" },
    {
        palabra_espanol: "Indígena serranía Kusii",
        palabra_wuayuunaiki: "Kusina",
    },
    { palabra_espanol: "Jagüey", palabra_wuayuunaiki: "Laa" },
    { palabra_espanol: "Lloriquear", palabra_wuayuunaiki: "Laayataa" },
    { palabra_espanol: "Balancearse", palabra_wuayuunaiki: "Lakantaa" },
    { palabra_espanol: "Redondo", palabra_wuayuunaiki: "Lakayaasu" },
    { palabra_espanol: "Laguna", palabra_wuayuunaiki: "Lamuuna" },
    {
        palabra_espanol: "Aseguranza wayuu - contra",
        palabra_wuayuunaiki: "Lania",
    },
    { palabra_espanol: "Cuchilla", palabra_wuayuunaiki: "Lapaa" },
    { palabra_espanol: "Sueño", palabra_wuayuunaiki: "Laapu" },
    { palabra_espanol: "Masa de maíz", palabra_wuayuunaiki: "Laujat" },
    { palabra_espanol: "Anciano", palabra_wuayuunaiki: "Laüla" },
    { palabra_espanol: "Autoridad", palabra_wuayuunaiki: "Laülaasüka" },
    { palabra_espanol: "Grueso", palabra_wuayuunaiki: "Lautasu" },
    { palabra_espanol: "Varicela", palabra_wuayuunaiki: "Lechiina" },
    { palabra_espanol: "Leche", palabra_wuayuunaiki: "Leechi" },
    { palabra_espanol: "Quejarse", palabra_wuayuunaiki: "Leenta" },
    { palabra_espanol: "Dar vuelta", palabra_wuayuunaiki: "Leeyataa" },
    { palabra_espanol: "Arrastrarse", palabra_wuayuunaiki: "Lemuttaa" },
    { palabra_espanol: "Despreciar", palabra_wuayuunaiki: "Letaa" },
    { palabra_espanol: "Dar vueltas", palabra_wuayuunaiki: "Leyataa" },
    { palabra_espanol: "Entre oscuro y claro", palabra_wuayuunaiki: "Lijotaa" },
    { palabra_espanol: "Limón", palabra_wuayuunaiki: "Limuuna" },
    {
        palabra_espanol: "Entrada del sol,atardecer.",
        palabra_wuayuunaiki: "Lokutaa",
    },
    { palabra_espanol: "Alambique", palabra_wuayuunaiki: "Lompiichi" },
    { palabra_espanol: "Derecho", palabra_wuayuunaiki: "Lotaa" },
    { palabra_espanol: "Línea recta", palabra_wuayuunaiki: "Lotuyaasü" },
    { palabra_espanol: "Arroyo", palabra_wuayuunaiki: "Lowopü" },
    { palabra_espanol: "Enrramada", palabra_wuayuunaiki: "Luma" },
    {
        palabra_espanol: "Vara de recoger iguaraya",
        palabra_wuayuunaiki: "Lumia - luuña",
    },
    { palabra_espanol: "Pujar", palabra_wuayuunaiki: "Lunita" },
    { palabra_espanol: "Piedra de afilar", palabra_wuayuunaiki: "Luta" },
    { palabra_espanol: "Color negro", palabra_wuayuunaiki: "Luuta" },
    { palabra_espanol: "Babosearse", palabra_wuayuunaiki: "Luuttaa" },
    { palabra_espanol: "Desaparecer volarse", palabra_wuayuunaiki: "Luwotaa" },
    { palabra_espanol: "Escaparse", palabra_wuayuunaiki: "Luwotaa" },
    { palabra_espanol: "Culebra cascabel", palabra_wuayuunaiki: "Ma>ala" },
    { palabra_espanol: "Loco", palabra_wuayuunaiki: "Ma>inica" },
    { palabra_espanol: "Miel", palabra_wuayuunaiki: "Ma>pa" },
    { palabra_espanol: "Antigua", palabra_wuayuunaiki: "Maalajatümaa" },
    { palabra_espanol: "Madrugada", palabra_wuayuunaiki: "Maalia" },
    {
        palabra_espanol: "Expresión para mujer mayor",
        palabra_wuayuunaiki: "Machee",
    },
    { palabra_espanol: "Sordo", palabra_wuayuunaiki: "Machee" },
    {
        palabra_espanol: "mujer esteril",
        palabra_wuayuunaiki: "Machonwaa / Marat",
    },
    { palabra_espanol: "Maíz", palabra_wuayuunaiki: "Maiki" },
    { palabra_espanol: "Municipio de Maicao", palabra_wuayuunaiki: "Maiko>u" },
    { palabra_espanol: "Bastante", palabra_wuayuunaiki: "Maima" },
    { palabra_espanol: "No hacer nada", palabra_wuayuunaiki: "Mainjalii" },
    { palabra_espanol: "Desdentado", palabra_wuayuunaiki: "Maisai" },
    { palabra_espanol: "Señorita", palabra_wuayuunaiki: "Majayut" },
    { palabra_espanol: "Verdad", palabra_wuayuunaiki: "Makalia" },
    { palabra_espanol: "Quedarse", palabra_wuayuunaiki: "Makataa" },
    { palabra_espanol: "Ser bobo", palabra_wuayuunaiki: "Malashi" },
    { palabra_espanol: "Dios", palabra_wuayuunaiki: "Male>eiwa" },
    { palabra_espanol: "Bejuco", palabra_wuayuunaiki: "Maliichi" },
    { palabra_espanol: "No es apreciado", palabra_wuayuunaiki: "Malinwaa" },
    { palabra_espanol: "Morrocón", palabra_wuayuunaiki: "Malokona" },
    { palabra_espanol: "Amarillo", palabra_wuayuunaiki: "Maloukatüsü" },
    { palabra_espanol: "Vacío", palabra_wuayuunaiki: "Malu>usat" },
    { palabra_espanol: "Malambo", palabra_wuayuunaiki: "Malua" },
    { palabra_espanol: "Colador", palabra_wuayuunaiki: "Manain" },
    { palabra_espanol: "Llevar la palabra", palabra_wuayuunaiki: "Mannaa" },
    { palabra_espanol: "Después", palabra_wuayuunaiki: "Mapao" },
    { palabra_espanol: "Piojos", palabra_wuayuunaiki: "Mapüi" },
    { palabra_espanol: "Botella", palabra_wuayuunaiki: "Maraaja" },
    { palabra_espanol: "Pagar", palabra_wuayuunaiki: "Matna" },
    { palabra_espanol: "Flor de abrojo", palabra_wuayuunaiki: "Matnasii" },
    { palabra_espanol: "Neblina", palabra_wuayuunaiki: "Matnuyaa" },
    { palabra_espanol: "Sin sabor", palabra_wuayuunaiki: "Meejüsat" },
    { palabra_espanol: "Mosquito", palabra_wuayuunaiki: "Mei" },
    { palabra_espanol: "Zancudo", palabra_wuayuunaiki: "Mei" },
    { palabra_espanol: "Número nueve (9)", palabra_wuayuunaiki: "Mekietsat" },
    { palabra_espanol: "Número ocho (8)", palabra_wuayuunaiki: "Mekiisat" },
    { palabra_espanol: "Buscar animales", palabra_wuayuunaiki: "Mereeraa" },
    { palabra_espanol: "Sumergirse", palabra_wuayuunaiki: "Mero>too" },
    { palabra_espanol: "Melón", palabra_wuayuunaiki: "Meruna" },
    { palabra_espanol: "Casa", palabra_wuayuunaiki: "Miichi" },
    { palabra_espanol: "Grande", palabra_wuayuunaiki: "Miou" },
    { palabra_espanol: "Tierra", palabra_wuayuunaiki: "Mma" },
    { palabra_espanol: "En el suelo", palabra_wuayuunaiki: "Mmalu>u" },
    { palabra_espanol: "Flor de abrojo", palabra_wuayuunaiki: "Mmasii" },
    { palabra_espanol: "Territorio", palabra_wuayuunaiki: "Mmpa>a" },
    { palabra_espanol: "Monte", palabra_wuayuunaiki: "Mojui" },
    { palabra_espanol: "Árbol de guamayo", palabra_wuayuunaiki: "Mokochira" },
    { palabra_espanol: "Bobo-pobreza", palabra_wuayuunaiki: "Molaa" },
    { palabra_espanol: "En el suelo", palabra_wuayuunaiki: "Molu" },
    { palabra_espanol: "Animales", palabra_wuayuunaiki: "Murüt" },
    { palabra_espanol: "Gato", palabra_wuayuunaiki: "Musa" },
    { palabra_espanol: "Caricari", palabra_wuayuunaiki: "Musale>e" },
    { palabra_espanol: "Carbór", palabra_wuayuunaiki: "Mushaisha / Mushainje" },
    { palabra_espanol: "Así es", palabra_wuayuunaiki: "Musia" },
    { palabra_espanol: "Color negro", palabra_wuayuunaiki: "Mutsiia" },
    { palabra_espanol: "Mula", palabra_wuayuunaiki: "Muula" },
    { palabra_espanol: "Toma", palabra_wuayuunaiki: "Na" },
    { palabra_espanol: "Sobre", palabra_wuayuunaiki: "Na>u" },
    { palabra_espanol: "Los-las-estos", palabra_wuayuunaiki: "Naa" },
    { palabra_espanol: "Estos", palabra_wuayuunaiki: "Nairua" },
    { palabra_espanol: "Parte alta", palabra_wuayuunaiki: "Namunau" },
    { palabra_espanol: "Aquellos", palabra_wuayuunaiki: "Nasairua" },
    { palabra_espanol: "Ellos", palabra_wuayuunaiki: "Naya" },
    { palabra_espanol: "Ellos", palabra_wuayuunaiki: "Nayairua" },
    { palabra_espanol: "Dinero", palabra_wuayuunaiki: "Neeru" },
    { palabra_espanol: "Animal castrado", palabra_wuayuunaiki: "Nevii" },
    { palabra_espanol: "El", palabra_wuayuunaiki: "Nia" },
    { palabra_espanol: "Negación", palabra_wuayuunaiki: "Nnojoo" },
    { palabra_espanol: "No hay", palabra_wuayuunaiki: "Nnojotsü" },
    { palabra_espanol: "No habrá", palabra_wuayuunaiki: "Nnololeerü" },
    { palabra_espanol: "Ojo de ellos", palabra_wuayuunaiki: "No>u" },
    { palabra_espanol: "Nuca", palabra_wuayuunaiki: "Nütkat" },
    { palabra_espanol: "Delante de él", palabra_wuayuunaiki: "Nupuleerua" },
    { palabra_espanol: "Enterrar", palabra_wuayuunaiki: "O>joitaa" },
    { palabra_espanol: "Bañarse", palabra_wuayuunaiki: "O>ojoo" },
    { palabra_espanol: "Partir-rajar", palabra_wuayuunaiki: "O>pulujaa" },
    { palabra_espanol: "Dejado-separado", palabra_wuayuunaiki: "O>ulaashi" },
    { palabra_espanol: "Adivinar", palabra_wuayuunaiki: "O>ulakaa" },
    { palabra_espanol: "Tobillera wayuu", palabra_wuayuunaiki: "O>uliijana" },
    { palabra_espanol: "Cuidar niños", palabra_wuayuunaiki: "O>ulijaa" },
    { palabra_espanol: "Ir", palabra_wuayuunaiki: "O>unaa" },
    { palabra_espanol: "Turismo-visitar", palabra_wuayuunaiki: "O>unajawaa" },
    { palabra_espanol: "Reclamar-discutir", palabra_wuayuunaiki: "O>uniirawa" },
    { palabra_espanol: "Langosta", palabra_wuayuunaiki: "O>unot" },
    { palabra_espanol: "Familia paterna", palabra_wuayuunaiki: "O>upayuu" },
    { palabra_espanol: "Cara", palabra_wuayuunaiki: "O>upunaa" },
    { palabra_espanol: "Gafas", palabra_wuayuunaiki: "O>usee" },
    { palabra_espanol: "Morir", palabra_wuayuunaiki: "O>utaa" },
    { palabra_espanol: "Pestaña", palabra_wuayuunaiki: "O>utaa" },
    { palabra_espanol: "Ojo", palabra_wuayuunaiki: "O>uu" },
    { palabra_espanol: "Edad", palabra_wuayuunaiki: "O>uyasse" },
    { palabra_espanol: "Sacar el agua", palabra_wuayuunaiki: "O>yonowaa" },
    { palabra_espanol: "Derramar-echar", palabra_wuayuunaiki: "O>yotoo" },
    { palabra_espanol: "Punzar", palabra_wuayuunaiki: "Ochonoo" },
    { palabra_espanol: "Cortar en pedazo", palabra_wuayuunaiki: "Ochonoojoo" },
    { palabra_espanol: "Bañarse", palabra_wuayuunaiki: "Ochoonojoo" },
    { palabra_espanol: "Tienda", palabra_wuayuunaiki: "Oikaalee" },
    { palabra_espanol: "Raspar", palabra_wuayuunaiki: "Ojoo" },
    { palabra_espanol: "Morder", palabra_wuayuunaiki: "Ojotta" },
    { palabra_espanol: "Afeitar-motilar", palabra_wuayuunaiki: "Ojüinjaa" },
    { palabra_espanol: "Salir", palabra_wuayuunaiki: "Ojuitaa" },
    { palabra_espanol: "Armar el chinchorro", palabra_wuayuunaiki: "Ojunaa" },
    { palabra_espanol: "Abrazar", palabra_wuayuunaiki: "Ojupajaa" },
    { palabra_espanol: "Abrazar-amparar", palabra_wuayuunaiki: "Ojuupujaa" },
    { palabra_espanol: "Mudarse", palabra_wuayuunaiki: "Okolojawaa" },
    { palabra_espanol: "Llevarse algo", palabra_wuayuunaiki: "Okolojoo" },
    { palabra_espanol: "Pescar", palabra_wuayuunaiki: "Olojoo" },
    { palabra_espanol: "Bramar de las vacas", palabra_wuayuunaiki: "Oloojoo" },
    { palabra_espanol: "Ombligo", palabra_wuayuunaiki: "Omochoo" },
    { palabra_espanol: "Moler", palabra_wuayuunaiki: "Omolojoo" },
    { palabra_espanol: "Pie", palabra_wuayuunaiki: "Oo>ilii" },
    { palabra_espanol: "Disecar cuero", palabra_wuayuunaiki: "Oojoo" },
    { palabra_espanol: "Ronquido", palabra_wuayuunaiki: "Ookolojoo" },
    { palabra_espanol: "Mazamorra", palabra_wuayuunaiki: "Ookotuushi" },
    { palabra_espanol: "Llagas-cáncer", palabra_wuayuunaiki: "Ooloko" },
    { palabra_espanol: "Toser-tuberculosis", palabra_wuayuunaiki: "Oonojoo" },
    { palabra_espanol: "Veranear", palabra_wuayuunaiki: "Oonowaa" },
    { palabra_espanol: "Culebra", palabra_wuayuunaiki: "Oorolia" },
    { palabra_espanol: "Aventado", palabra_wuayuunaiki: "Oorotsü" },
    {
        palabra_espanol: "Hacer derramar-bautizar",
        palabra_wuayuunaiki: "Ooyotiraa",
    },
    { palabra_espanol: "Cobrar", palabra_wuayuunaiki: "Opotoo" },
    { palabra_espanol: "Aventado", palabra_wuayuunaiki: "Orotsu" },
    { palabra_espanol: "Punto", palabra_wuayuunaiki: "Osonalaaya" },
    { palabra_espanol: "Preparar alimentos", palabra_wuayuunaiki: "Otnajaa" },
    { palabra_espanol: "Caerse", palabra_wuayuunaiki: "Otnojowaa" },
    { palabra_espanol: "Sacudir", palabra_wuayuunaiki: "Otojowaa" },
    { palabra_espanol: "Y", palabra_wuayuunaiki: "Otta" },
    { palabra_espanol: "Empezar", palabra_wuayuunaiki: "Ottaa" },
    { palabra_espanol: "Riña-pelea", palabra_wuayuunaiki: "Ottirawaa" },
    { palabra_espanol: "Visitar", palabra_wuayuunaiki: "Ounajawaa" },
    { palabra_espanol: "Raíz", palabra_wuayuunaiki: "Ouralaa" },
    { palabra_espanol: "Encontrar", palabra_wuayuunaiki: "Oustaa" },
    { palabra_espanol: "Reunirse", palabra_wuayuunaiki: "Outkajaa" },
    { palabra_espanol: "Médico tradicional", palabra_wuayuunaiki: "Outsü" },
    { palabra_espanol: "Vaca", palabra_wuayuunaiki: "Paa>a" },
    { palabra_espanol: "Cuero de vaca", palabra_wuayuunaiki: "Paa>ata" },
    { palabra_espanol: "Carne de res", palabra_wuayuunaiki: "Paa>iruku" },
    {
        palabra_espanol: "Lluvias entre diciembre y enero",
        palabra_wuayuunaiki: "Paama",
    },
    { palabra_espanol: "Mar", palabra_wuayuunaiki: "Palaa" },
    { palabra_espanol: "Primero", palabra_wuayuunaiki: "Palaajana" },
    { palabra_espanol: "Hacia el mar-norte", palabra_wuayuunaiki: "Palaamüin" },
    { palabra_espanol: "Salado", palabra_wuayuunaiki: "Palaassü" },
    { palabra_espanol: "Waimaro", palabra_wuayuunaiki: "Paleensa" },
    { palabra_espanol: "Poco", palabra_wuayuunaiki: "Palitchon/Paliitsu" },
    { palabra_espanol: "Celebridad", palabra_wuayuunaiki: "Pansawaa" },
    { palabra_espanol: "Nombre de la", palabra_wuayuunaiki: "Paralüelu>u" },
    { palabra_espanol: "Pichiwel", palabra_wuayuunaiki: "Paruluwaa" },
    {
        palabra_espanol: "Medida de capacidad equivalente a 20 litros",
        palabra_wuayuunaiki: "Pasaana",
    },
    { palabra_espanol: "En el medio", palabra_wuayuunaiki: "Pasaanain" },
    {
        palabra_espanol: "Angosto Comunidad de Puerto Estrella (Alta-Guajira)",
        palabra_wuayuunaiki: "Pasanua",
    },
    { palabra_espanol: "Árbol Piona", palabra_wuayuunaiki: "Patsua" },
    { palabra_espanol: "Dentro de la casa", palabra_wuayuunaiki: "Paulü" },
    { palabra_espanol: "Número dos (2)", palabra_wuayuunaiki: "Piama" },
    { palabra_espanol: "Número cuatro (4)", palabra_wuayuunaiki: "Pienchi" },
    { palabra_espanol: "Sustituir", palabra_wuayuunaiki: "Pii>iraka" },
    { palabra_espanol: "Casa", palabra_wuayuunaiki: "Piichi" },
    { palabra_espanol: "Mira", palabra_wuayuunaiki: "Piirakaa" },
    { palabra_espanol: "Lleno hasta el borde", palabra_wuayuunaiki: "Pirataa" },
    { palabra_espanol: "Frenos del burro", palabra_wuayuunaiki: "Pisaalu" },
    { palabra_espanol: "Burro", palabra_wuayuunaiki: "Piliiki" },
    { palabra_espanol: "Frijol guajiro", palabra_wuayuunaiki: "Pitchushii" },
    { palabra_espanol: "Oscuro", palabra_wuayuunaiki: "Piushii" },
    { palabra_espanol: "Número diez (10)", palabra_wuayuunaiki: "Po>loo" },
    { palabra_espanol: "Enfermedad-fiebre", palabra_wuayuunaiki: "Poloono" },
    { palabra_espanol: "Resbaloso-barroso", palabra_wuayuunaiki: "Pooposhi" },
    { palabra_espanol: "Barro", palabra_wuayuunaiki: "Potshi" },
    { palabra_espanol: "Cartelera", palabra_wuayuunaiki: "Püchimaajatü" },
    { palabra_espanol: "Puerco espín", palabra_wuayuunaiki: "Püichi" },
    { palabra_espanol: "Misterioso", palabra_wuayuunaiki: "Pulasü" },
    {
        palabra_espanol: "Piedra preciosa de forma alargada",
        palabra_wuayuunaiki: "Pülaulia",
    },
    { palabra_espanol: "Tibio", palabra_wuayuunaiki: "Pulayaa/Puyutsu" },
    { palabra_espanol: "Lugar encantado", palabra_wuayuunaiki: "Puloi" },
    { palabra_espanol: "Murciélago", palabra_wuayuunaiki: "Püssichi" },
    { palabra_espanol: "Palabra", palabra_wuayuunaiki: "Pütchi" },
    { palabra_espanol: "Palabrero", palabra_wuayuunaiki: "Pütchipü" },
    { palabra_espanol: "Oración", palabra_wuayuunaiki: "Pütcho> ulia" },
    { palabra_espanol: "Frase", palabra_wuayuunaiki: "Pütcho>uliayaasü" },
    { palabra_espanol: "Barra de chinchorro", palabra_wuayuunaiki: "Puui" },
    { palabra_espanol: "Color gris", palabra_wuayuunaiki: "Ratuuna" },
    { palabra_espanol: "Fatiga", palabra_wuayuunaiki: "Rereetaa" },
    { palabra_espanol: "Maleza", palabra_wuayuunaiki: "Rerechee" },
    { palabra_espanol: "Cuchara de café", palabra_wuayuunaiki: "Rimion" },
    { palabra_espanol: "Chipichipi", palabra_wuayuunaiki: "Ripiripii" },
    { palabra_espanol: "Espejo", palabra_wuayuunaiki: "Rouya" },
    { palabra_espanol: "Cuchillo", palabra_wuayuunaiki: "Rüi" },
    { palabra_espanol: "Bolsa de trapo", palabra_wuayuunaiki: "Ruiluu" },
    { palabra_espanol: "Vigilado", palabra_wuayuunaiki: "Ruleeya" },
    { palabra_espanol: "Sábila", palabra_wuayuunaiki: "Ruliipü/Ruipi" },
    { palabra_espanol: "Comején", palabra_wuayuunaiki: "Ruluma" },
    { palabra_espanol: "Algo pegajoso", palabra_wuayuunaiki: "Rutta" },
    { palabra_espanol: "Entre algo", palabra_wuayuunaiki: "Sa>aka" },
    { palabra_espanol: "Encima", palabra_wuayuunaiki: "Sa>u" },
    { palabra_espanol: "Al lado", palabra_wuayuunaiki: "Saato>u" },
    { palabra_espanol: "Al terminar", palabra_wuayuunaiki: "Sajattia" },
    { palabra_espanol: "Montuno-brioso", palabra_wuayuunaiki: "Samoluuna" },
    { palabra_espanol: "Gallinazo", palabra_wuayuunaiki: "Samut" },
    { palabra_espanol: "Anamú", palabra_wuayuunaiki: "Samuttapai" },
    { palabra_espanol: "Clan wayuu", palabra_wuayuunaiki: "Sapuana" },
    { palabra_espanol: "Boa", palabra_wuayuunaiki: "Sarut" },
    { palabra_espanol: "Tortuga", palabra_wuayuunaiki: "Sawainru" },
    { palabra_espanol: "Cebo", palabra_wuayuunaiki: "Seepu" },
    { palabra_espanol: "Mellizos", palabra_wuayuunaiki: "Senkeeyuu" },
    { palabra_espanol: "Colador", palabra_wuayuunaiki: "Sesee" },
    {
        palabra_espanol: "Vestimenta típica wayuu(wayuuko)",
        palabra_wuayuunaiki: "Sii>raa",
    },
    {
        palabra_espanol: "Comunidad wayuu(nazarteh alta guajira)",
        palabra_wuayuunaiki: "Siiapana",
    },
    { palabra_espanol: "Carne salada", palabra_wuayuunaiki: "Siinaa" },
    { palabra_espanol: "Clan wayuu", palabra_wuayuunaiki: "Sijona" },
    { palabra_espanol: "Pulido", palabra_wuayuunaiki: "Sinatüsü" },
    {
        palabra_espanol: "Material de diseñar mucura",
        palabra_wuayuunaiki: "Sirua",
    },
    { palabra_espanol: "Nube", palabra_wuayuunaiki: "Siruma" },
    { palabra_espanol: "Caldero", palabra_wuayuunaiki: "Siwarai" },
    { palabra_espanol: "Manea del caballo", palabra_wuayuunaiki: "Siwottaa" },
    { palabra_espanol: "Recreación wayuu", palabra_wuayuunaiki: "So>ula" },
    { palabra_espanol: "Semilla", palabra_wuayuunaiki: "Su>u" },
    { palabra_espanol: "Riohacha", palabra_wuayuunaiki: "Suchimaa" },
    { palabra_espanol: "Detrás de", palabra_wuayuunaiki: "Suchirua" },
    { palabra_espanol: "Cielo", palabra_wuayuunaiki: "Sueumatu>u" },
    { palabra_espanol: "Chinchorro", palabra_wuayuunaiki: "Sui" },
    { palabra_espanol: "Porque", palabra_wuayuunaiki: "Süka" },
    {
        palabra_espanol: "Entre medio de algo",
        palabra_wuayuunaiki: "Sülatiralu>u",
    },
    { palabra_espanol: "Dentro de", palabra_wuayuunaiki: "Sulu>u" },
    { palabra_espanol: "Antiguo", palabra_wuayuunaiki: "Sumaiwa" },
    { palabra_espanol: "Reflejo (luz)", palabra_wuayuunaiki: "Sumaralaa" },
    { palabra_espanol: "Piso", palabra_wuayuunaiki: "Süpa>a" },
    { palabra_espanol: "Hoja", palabra_wuayuunaiki: "Supana" },
    { palabra_espanol: "Para", palabra_wuayuunaiki: "Süpüla" },
    { palabra_espanol: "Todo", palabra_wuayuunaiki: "Supushua>aya" },
    { palabra_espanol: "Flor", palabra_wuayuunaiki: "Susii" },
    { palabra_espanol: "Mochila", palabra_wuayuunaiki: "Susu" },
    { palabra_espanol: "Usa", palabra_wuayuunaiki: "Sutta" },
    { palabra_espanol: "Debajo", palabra_wuayuunaiki: "Suupuna" },
    { palabra_espanol: "Debajo de", palabra_wuayuunaiki: "Suutpu>naa" },
    {
        palabra_espanol: "Alimento wayuu(mazamorra)",
        palabra_wuayuunaiki: "Wa>a",
    },
    { palabra_espanol: "Entre nosotros", palabra_wuayuunaiki: "Wa>aka" },
    {
        palabra_espanol: "Pasar lejos de nuestro lado",
        palabra_wuayuunaiki: "Wa>atapuuna",
    },
    { palabra_espanol: "Instrumento musical", palabra_wuayuunaiki: "Wa>wai" },
    { palabra_espanol: "Millo", palabra_wuayuunaiki: "Waana" },
    { palabra_espanol: "Bastante", palabra_wuayuunaiki: "Waima" },
    { palabra_espanol: "Plural", palabra_wuayuunaiki: "Waimayaasü" },
    { palabra_espanol: "No sé", palabra_wuayuunaiki: "Wainja" },
    { palabra_espanol: "Palguarata", palabra_wuayuunaiki: "Wainpirai" },
    { palabra_espanol: "Abierto", palabra_wuayuunaiki: "Wakataa" },
    { palabra_espanol: "Nuestra costumbre", palabra_wuayuunaiki: "Wakua>ipa" },
    { palabra_espanol: "Muñeca de oro", palabra_wuayuunaiki: "Walaa" },
    { palabra_espanol: "Calor", palabra_wuayuunaiki: "Walatshi" },
    { palabra_espanol: "Mi estomago", palabra_wuayuunaiki: "Wale>e" },
    { palabra_espanol: "Araña", palabra_wuayuunaiki: "Walekeerü" },
    { palabra_espanol: "Oso hormiguero", palabra_wuayuunaiki: "Wali>i" },
    { palabra_espanol: "Zorro", palabra_wuayuunaiki: "Walit" },
    { palabra_espanol: "Cataneja", palabra_wuayuunaiki: "Waluuseechi" },
    { palabra_espanol: "Equidad", palabra_wuayuunaiki: "Wanaawaa ajutu" },
    { palabra_espanol: "Uno", palabra_wuayuunaiki: "Wanee" },
    { palabra_espanol: "Diferente", palabra_wuayuunaiki: "Waneejatu" },
    { palabra_espanol: "Siempre-entero", palabra_wuayuunaiki: "Waneepia" },
    { palabra_espanol: "Ser mítico", palabra_wuayuunaiki: "Waneesatai" },
    { palabra_espanol: "Unitario", palabra_wuayuunaiki: "Waneesüin akua>ipa" },
    { palabra_espanol: "Unidad", palabra_wuayuunaiki: "Waneeyaasü" },
    { palabra_espanol: "Nuestro idioma", palabra_wuayuunaiki: "Wanüiki" },
    { palabra_espanol: "Enfermedad", palabra_wuayuunaiki: "Wanülüü" },
    { palabra_espanol: "Del lado abajo", palabra_wuayuunaiki: "Wapunna" },
    { palabra_espanol: "Familia", palabra_wuayuunaiki: "Wapüshi" },
    { palabra_espanol: "Bejuco", palabra_wuayuunaiki: "Waraarat" },
    { palabra_espanol: "Caminar", palabra_wuayuunaiki: "Waraita" },
    { palabra_espanol: "Gavilán", palabra_wuayuunaiki: "Warulapain" },
    { palabra_espanol: "Caracol", palabra_wuayuunaiki: "Warutta" },
    { palabra_espanol: "Nuestra ropa", palabra_wuayuunaiki: "Washein" },
    { palabra_espanol: "Rico", palabra_wuayuunaiki: "Washit" },
    { palabra_espanol: "Calamar", palabra_wuayuunaiki: "Washuchon" },
    { palabra_espanol: "Lebranche", palabra_wuayuunaiki: "Wasikit" },
    { palabra_espanol: "Mañana", palabra_wuayuunaiki: "Watta>a" },
    { palabra_espanol: "Lejos", palabra_wuayuunaiki: "Wattasü" },
    { palabra_espanol: "Pasado mañana", palabra_wuayuunaiki: "Wattepia>a" },
    { palabra_espanol: "Una vez", palabra_wuayuunaiki: "Watua" },
    { palabra_espanol: "Tortolita", palabra_wuayuunaiki: "Wawaachi" },
    { palabra_espanol: "Huracán", palabra_wuayuunaiki: "Wawain" },
    {
        palabra_espanol: "Comunidad de Portete",
        palabra_wuayuunaiki: "Wawaliwo>u",
    },
    { palabra_espanol: "Nuestra lengua", palabra_wuayuunaiki: "Wayee" },
    { palabra_espanol: "Persona indígena", palabra_wuayuunaiki: "Wayuu" },
    { palabra_espanol: "Todo el tiempo", palabra_wuayuunaiki: "Wenshi" },
    { palabra_espanol: "En nuestra casa", palabra_wuayuunaiki: "Wepiali>u" },
    { palabra_espanol: "Comunidad", palabra_wuayuunaiki: "Wepiapa>a" },
    { palabra_espanol: "Nuestro ojo", palabra_wuayuunaiki: "Wo>u" },
    {
        palabra_espanol: "No importa-sin cuidado",
        palabra_wuayuunaiki: "Wo>ulia",
    },
    {
        palabra_espanol: "Instrumento musical",
        palabra_wuayuunaiki: "Wontoroyoui",
    },
    { palabra_espanol: "Nuestro Pie", palabra_wuayuunaiki: "Woo>ui" },
    { palabra_espanol: "Camino…", palabra_wuayuunaiki: "Wopü" },
    { palabra_espanol: "Aquí", palabra_wuayuunaiki: "Ya>aya" },
    {
        palabra_espanol: "Medida de tamaño-quedarse",
        palabra_wuayuunaiki: "Yaainchi",
    },
    { palabra_espanol: "Tuatua", palabra_wuayuunaiki: "Yaichua" },
    { palabra_espanol: "Yuca brava", palabra_wuayuunaiki: "Yaishi" },
    { palabra_espanol: "Bollo de mazorca", palabra_wuayuunaiki: "Yaja" },
    { palabra_espanol: "Mazamorra de leche", palabra_wuayuunaiki: "Yajaaushi" },
    { palabra_espanol: "Entre abierto", palabra_wuayuunaiki: "Yakataa" },
    { palabra_espanol: "Allá-ahí", palabra_wuayuunaiki: "Yala>aya" },
    { palabra_espanol: "Áspero", palabra_wuayuunaiki: "Yalaasü" },
    { palabra_espanol: "Por allá", palabra_wuayuunaiki: "Yalapunna" },
    { palabra_espanol: "Desde lado", palabra_wuayuunaiki: "Yale>eru" },
    { palabra_espanol: "Pez sábalo", palabra_wuayuunaiki: "Yamüla" },
    { palabra_espanol: "Estar abatido", palabra_wuayuunaiki: "Yamülaa" },
    { palabra_espanol: "Trabajo colectivo", palabra_wuayuunaiki: "Yanama" },
    { palabra_espanol: "Estar listo-preparado", palabra_wuayuunaiki: "Yapaa" },
    { palabra_espanol: "Estar listo", palabra_wuayuunaiki: "Yapashi" },
    { palabra_espanol: "Sucio", palabra_wuayuunaiki: "Yarutaa" },
    { palabra_espanol: "Elegancia-riqueza", palabra_wuayuunaiki: "Yatetaa" },
    { palabra_espanol: "Pringamoza", palabra_wuayuunaiki: "Yawa" },
    { palabra_espanol: "Apagado", palabra_wuayuunaiki: "Yokutaa" },
    {
        palabra_espanol: "Nombre de sitios wayuu",
        palabra_wuayuunaiki: "Yokuyokui",
    },
    { palabra_espanol: "Alcatraz", palabra_wuayuunaiki: "Yolijaa" },
    { palabra_espanol: "Baile típico", palabra_wuayuunaiki: "Yonna" },
    { palabra_espanol: "Herida", palabra_wuayuunaiki: "Yooi" },
    {
        palabra_espanol: "Ron artesanal de los wayuu ,chirrinche",
        palabra_wuayuunaiki: "Yootshi",
    },
    { palabra_espanol: "Conversar:", palabra_wuayuunaiki: "Yorolo" },
    {
        palabra_espanol: "Zanja hecha por una corriente de agua",
        palabra_wuayuunaiki: "Yoroloma",
    },
    { palabra_espanol: "Cardón", palabra_wuayuunaiki: "Yosù" },
    {
        palabra_espanol: "Corazón del cardón, material para hacer casas wayuu",
        palabra_wuayuunaiki: "Yotojoro",
    },
    { palabra_espanol: "Retoñar", palabra_wuayuunaiki: "Yotoo" },
    { palabra_espanol: "Fécula de maíz", palabra_wuayuunaiki: "Youula" },
    { palabra_espanol: "Quebrado-partir", palabra_wuayuunaiki: "Yulaa" },
    { palabra_espanol: "Espíritu maligno", palabra_wuayuunaiki: "Yulujaa" },
    { palabra_espanol: "Estirarse", palabra_wuayuunaiki: "Yuttaa" },
    { palabra_espanol: "Lugar-desierto-solo", palabra_wuayuunaiki: "Yütuu" },
    { palabra_espanol: "Rosa-huerta", palabra_wuayuunaiki: "Yüüja" },
    { palabra_espanol: "Mecer-caminar", palabra_wuayuunaiki: "Yuunataa" },
    { palabra_espanol: "Color negro", palabra_wuayuunaiki: "Yuuuisü" },
];

const gameContainer = document.getElementById("game");

let cantPreg = 0;
let pregCorr = 0;

function iniciarJuego() {
    const palabraObj = palabras[Math.floor(Math.random() * palabras.length)];
    const palabraCompleta = palabraObj.palabra_wuayuunaiki;
    const palabra_espanol = palabraObj.palabra_espanol;
    const indiceAleatorio = Math.floor(Math.random() * palabraCompleta.length);
    const letraFaltante = palabraCompleta[indiceAleatorio];
    const palabraConBlanco =
        palabraCompleta.slice(0, indiceAleatorio) +
        "_" +
        palabraCompleta.slice(indiceAleatorio + 1);

    const opciones = generarOpciones(letraFaltante);
    mostrarJuego(palabra_espanol, palabraConBlanco, opciones, letraFaltante);
}

function generarOpciones(letraCorrecta) {
    const letras = [
        "a",
        "e",
        "i",
        "o",
        "u",
        "ü",
        "c",
        "j",
        "k",
        "l",
        "m",
        "n",
        "ñ",
        "p",
        "r",
        "s",
        "h",
        "t",
        "v",
        "w",
        "y",
        ">",
    ];
    let opciones = [letraCorrecta];

    while (opciones.length < 4) {
        const letraAleatoria =
            letras[Math.floor(Math.random() * letras.length)];
        if (!opciones.includes(letraAleatoria)) {
            opciones.push(letraAleatoria);
        }
    }

    return opciones.sort(() => Math.random() - 0.5);
}

function mostrarJuego(palabra_espanol, palabra, opciones, letraCorrecta) {
    gameContainer.innerHTML = `
        <h1>Completa la palabra: <br></h1>
        <span>${palabra_espanol}</span><br>
        <h2> ${palabra}</h2>
        <div class="letters">
            ${opciones
                .map(
                    (letra) =>
                        `<button onclick="verificarRespuesta(this,'${letra}', '${letraCorrecta}')">${letra}</button>`
                )
                .join("")}
        </div>
    `;
    cantPreg++;
}

function verificarRespuesta(element, letraSeleccionada, letraCorrecta) {
    let contenedor = document.querySelector(".letters");

    contenedor.classList.add("bloquearLetter");

    if (letraSeleccionada === letraCorrecta) {
        element.classList.add("correcta");
        pregCorr++;
    } else {
        element.classList.add("incorrecta");
    }

    setTimeout(() => {
        element.classList.remove("correcta");
        element.classList.remove("incorrecta");
        if (cantPreg <= 10) {
            iniciarJuego();
        } else {
            resultadoFinal();
        }

        contenedor.classList.remove("bloquearLetter");
    }, 5000);
}

$(document).ready(function () {
    abrirModal();
});

function resultadoFinal() {
    $("#principal").fadeToggle(500);
    setTimeout(() => {
        $("#final").fadeToggle(1000);
    }, 500);
    if (pregCorr >= 6) {
        document.getElementById("final").style.backgroundImage =
            "url(../../images/victoria.gif)";
    } else {
        document.getElementById("final").style.backgroundImage =
            "url(../../images/derrota.gif)";
    }

    document.getElementById("texto_final").innerText =
        "Has identificado correctamente " + pregCorr + "  palabras de 10";
}

function abrirModal() {
    Swal.fire({
        title: "<strong>Juego de Completa</strong>",
        type: "info",
        html: "En este juego deberás ingresar la vocal o consonante faltante en la palabra para poder ganar.",
        showCloseButton: true,
        showCancelButton: true,
        focusConfirm: false,
        confirmButtonText: '<i class="fa fa-thumbs-up"></i> Vamos!',
        confirmButtonAriaLabel: "Thumbs up, great!",
        cancelButtonText: '<i class="fa fa-thumbs-down"></i>',
        cancelButtonAriaLabel: "Thumbs down",
        confirmButtonClass: "btn btn-primary",
        buttonsStyling: false,
        cancelButtonClass: "btn btn-danger ml-1",
    }).then((result) => {
        if (result.value) {
            // Se ha hecho clic en el botón "Aceptar"
            // Llama a la función que deseas ejecutar
            activarPantallaCompleta();
            iniciarJuego();
        } else if (result.dismiss === Swal.DismissReason.cancel) {
            // Se ha hecho clic en el botón "Cancelar"
            // Regresa a la página anterior
            window.history.back();
        }
    });
}

function activarPantallaCompleta() {
    if (document.documentElement.requestFullscreen) {
        document.documentElement.requestFullscreen();
    } else if (document.documentElement.mozRequestFullScreen) {
        document.documentElement.mozRequestFullScreen();
    } else if (document.documentElement.webkitRequestFullscreen) {
        document.documentElement.webkitRequestFullscreen();
    } else if (document.documentElement.msRequestFullscreen) {
        document.documentElement.msRequestFullscreen();
    }
}
